site_name: My Docs

# mkdocs.yml
theme:
  name: "material"

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Introduction: 'index.md'
  - Installation: 'installation.md'
  - Quick Start: 'quickstart.md'
  - Advanced Usage: 'advancedUsage.md'
  # - Ticker: 'Ticker.md'
  - TickerBase: 'TickerBase.md'
  # - Tickers: 'Tickers.md'
  - utils: 'utils.md'
  - multi: 'multi.md'
