name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - dev-documented

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install Sphinx==8.0.2 pydata-sphinx-theme==0.15.4 Jinja2==3.1.4 sphinx-copybutton==0.5.2

    - name: Build Sphinx documentation
      run: |
        sphinx-build -b html doc/source doc/_build/html -v

    - name: List generated HTML files
      run: |
        ls -l -R doc/_build/html

    - name: Deploy to dev-documented branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        git checkout dev-documented

        mkdir -p docs
        rm -rf docs/*
        cp -r doc/_build/html/* docs/
        touch docs/.nojekyll
        
        git add -f docs
        git commit -m "Update documentation"
        git push origin dev-documented