name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - documentation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Sphinx documentation
      run: |
        sphinx-build -b html doc/source doc/build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: documentation
        publish_dir: doc/build/html
        destination_dir: docs
        enable_jekyll: false