name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - safe_pr

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8.12']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests_cache>=1.0 requests_ratelimiter>=0.3.1 scipy>=1.6.3

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests -v